- name: Installer les dépendances de base
  apt:
    name: [git, nodejs, npm]
    update_cache: yes

- name: Installer PM2 globalement
  npm:
    name: pm2
    global: yes

- name: Cloner l'application depuis Git
  git:
    repo: 'https://github.com/kpajro/deploy_app.git'
    dest: deployapp
    version: main
    force: yes

- name: Installer les dépendances NPM
  npm:
    path: deployapp
    production: yes

- name: Start the app with PM2 as azureuser
  become: true
  become_user: azureuser
  command: pm2 -f start /home/azureuser/deployapp/server.js

- name: Générer la commande de démarrage auto
  command: pm2 startup systemd
  register: pm2_startup

- name: Sauvegarder l'état PM2
  command: pm2 save
